const types = {
    USER_AUTHENTICATED : 'USER_AUTHENTICATED',
    USER_DISCONNECTED : 'USER_DISCONNECTED',
    GET_USER : 'GET_USER',
    MESSAGE_ADDED : 'MESSAGE_ADDED',
    ADD_COMMENT : 'ADD_COMMENT',
    CHANNEL_CHANGE : 'CHANNEL_CHANGE',
    CHANNEL_ADD : 'CHANNEL_ADD',
    CHANNEL_LIST : 'CHANNEL_LIST',
}

export default types